version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8075:8075"
    volumes:
      - ./Warehouse_v6:/Warehouse_v6
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8075"
