version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8075:8075"
    volumes:
      - ./Warehouse_v6:/Warehouse_v6
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runsslserver 0.0.0.0:8075"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=bv4811ss
    depends_on:
      - db
    networks:
      - warehouse-network

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=bv4811ss
    networks:
      - warehouse-network

networks:
  warehouse-network:
    external: true

volumes:
  dev-db-data:
